### ISSUE TITLE
Question about airflow version consistency

### ISSUE THREAD

**Issue by sakaia** [NetAppDocs/netapp-solutions#28]
On Airflow by Pip3 installation environment, sample code works fine.

but on Airflow by helm environment, almost works but some problem.

airflow backfill works with `-x` option for PythonOperator.
But airflow-worker container package problem still remain, Is there any method to solve this?

```
ERROR: apache-airflow 1.10.14 requires flask-appbuilder~=2.2; python_version >= "3.6", but you'll have flask-appbuilder 3.1.1 which is incompatible.
ERROR: netapp-ontap 9.8.0 requires marshmallow>=3.2.1, but you'll have marshmallow 2.21.0 which is incompatible.
ERROR: flask-appbuilder 2.3.4 requires marshmallow<3.0.0,>=2.18.0, but you'll have marshmallow 3.0.0rc7 which is incompatible.
```

**Comment by mboglesby** [comment]
@sakaia - Which example workflow are you attempting to run? Also, which executor are you using?

**Comment by sakaia** [comment]
I am simplify the AI Training code for Testing.
In my HELM environment, PythonOperator works fine. but with netapp-ontap module, it fails.
But on my PIP environment, sample code with netapp-ontap works fine. 
Any suggestions are appreciate.

The testing code (simplify AI Trining code ) is follows.

```
# Airflow DAG Definition: Snapshot for Airflow Helm
#
# Steps:
# 4. Model snapshot (for versioning/baselining)

from airflow.utils.dates import days_ago
from airflow.secrets import get_connections
from airflow.models import DAG
from airflow.operators.python_operator import PythonOperator
from airflow.operators.bash_operator import BashOperator

##### DEFINE PARAMETERS: Modify parameter values in this section to match your environment #####
## Define default args for DAG
ai_training_run_dag_default_args = {
    'owner': 'NetApp'
}

## Define DAG details
ai_training_run_dag = DAG(
    dag_id='snapshot2',
    default_args=ai_training_run_dag_default_args,
    schedule_interval=None,
    start_date=days_ago(2),
    tags=['training']
)
## Define volume details (change values as necessary to match your environment)

# ONTAP system details
airflowConnectionName = 'ontap_ai' # Name of the Airflow connection that contains connection details for your ONTAP system's cluster admin account
verifySSLCert = False # Denotes whether or not to verify the SSL cert when calling the ONTAP API

# Model volume
## test for snapshot
model_volume_pv_name = 'pvc-ab8c7f2b-1e8b-4758-acfd-6f698782efd8'

################################################################################################
# Define function that triggers the creation of a NetApp snapshot
def netappSnapshot(**kwargs) -> str :
    # Parse args
    for key, value in kwargs.items() :
        if key == 'pvName' :
            pvName = value
        elif key == 'verifySSLCert' :
            verifySSLCert = value
        elif key == 'airflowConnectionName' :
            airflowConnectionName = value

    # Install netapp_ontap package
    import sys, subprocess
    result = subprocess.check_output([sys.executable, '-m', 'pip', 'install', '--user', 'netapp-ontap'])
    # HELM environment
    #result = subprocess.check_output([sys.executable, '-m', 'pip', 'install', '--user', 'netapp-ontap','--use-feature=2020-resolver'])
    print(str(result).replace('\\n', '\n'))

    # Import needed functions/classes
    from netapp_ontap import config as netappConfig
    from netapp_ontap.host_connection import HostConnection as NetAppHostConnection
    from netapp_ontap.resources import Volume, Snapshot
    from datetime import datetime
    import json

    # Retrieve ONTAP cluster admin account details from Airflow connection
    connections = get_connections(conn_id = airflowConnectionName)
    ontapConnection = connections[0] # Assumes that you only have one connection with the specified conn_id configured in Airflow
    ontapClusterAdminUsername = ontapConnection.login
    ontapClusterAdminPassword = ontapConnection.password
    ontapClusterMgmtHostname = ontapConnection.host
    # Configure connection to ONTAP cluster/instance
    netappConfig.CONNECTION = NetAppHostConnection(
        host = ontapClusterMgmtHostname,
        username = ontapClusterAdminUsername,
        password = ontapClusterAdminPassword,
        verify = verifySSLCert
    )

    # Convert pv name to ONTAP volume name
    # The following will not work if you specified a custom storagePrefix when creating your
    # Trident backend. If you specified a custom storagePrefix, you will need to update this
    # code to match your prefix.
    volumeName = 'trident_%s' % pvName.replace("-", "_")
    print('\npv name: ', pvName)
    print('ONTAP volume name: ', volumeName)

    # Create snapshot; print API response
    volume = Volume.find(name = volumeName)
    timestamp = datetime.today().strftime("%Y%m%d_%H%M%S")
    snapshot = Snapshot.from_dict({
        'name': 'airflow_%s' % timestamp,
        'comment': 'Snapshot created by a Apache Airflow DAG',
        'volume': volume.to_dict()
    })
    response = snapshot.post()
    print("\nAPI Response:")
    print(response.http_response.text)

    # Retrieve snapshot details
    snapshot.get()
    # Convert snapshot details to JSON string and print
    snapshotDetails = snapshot.to_dict()
    print("\nSnapshot Details:")
    print(json.dumps(snapshotDetails, indent=2))

    # Return name of newly created snapshot
    return snapshotDetails['name']

# Define DAG steps/workflow
with ai_training_run_dag as dag :
    model_snapshot = PythonOperator(
        task_id='model-snapshot',
        python_callable=netappSnapshot,
        op_kwargs={
            'airflowConnectionName': airflowConnectionName,
            'pvName': model_volume_pv_name,
            'verifySSLCert': verifySSLCert
        },
        dag=dag
    )
```
The error message for airflow-worker is follows.

```
[2021-02-03 07:21:55,537] {settings.py:233} DEBUG - Setting up DB connection pool (PID 1)
[2021-02-03 07:21:55,537] {settings.py:300} DEBUG - settings.prepare_engine_args(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=1
[2021-02-03 07:21:55,806] {sentry.py:179} DEBUG - Could not configure Sentry: No module named 'blinker', using DummySentry instead.
[2021-02-03 07:21:55,846] {__init__.py:45} DEBUG - Cannot import  due to  doesn't look like a module path
[2021-02-03 07:21:56,172] {cli_action_loggers.py:42} DEBUG - Adding <function default_action_log at 0x7fb603772950> to pre execution callback
[2021-02-03 07:21:56,978] {cli_action_loggers.py:68} DEBUG - Calling callbacks: [<function default_action_log at 0x7fb603772950>]
[2021-02-03 07:21:57,015] {settings.py:233} DEBUG - Setting up DB connection pool (PID 1)
[2021-02-03 07:21:57,016] {settings.py:267} DEBUG - settings.prepare_engine_args(): Using NullPool
[2021-02-03 07:21:57,019] {__init__.py:50} INFO - Using executor LocalExecutor
[2021-02-03 07:21:57,020] {dagbag.py:417} INFO - Filling up the DagBag from /opt/airflow/dags/tr4798ss.py
[2021-02-03 07:21:57,023] {dagbag.py:245} DEBUG - Importing /opt/airflow/dags/tr4798ss.py
[2021-02-03 07:21:57,032] {dagbag.py:384} DEBUG - Loaded DAG <DAG: snapshot2>
[2021-02-03 07:21:57,032] {dagbag.py:384} DEBUG - Loaded DAG <DAG: snapshot2>
Running <TaskInstance: snapshot2.model-snapshot 2020-12-02T00:00:00+00:00 [queued]> on host snapshot2modelsnapshot-f835dc9d847f4483b49dc5702dec315d
ERROR: flask-appbuilder 2.3.4 requires marshmallow<3.0.0,>=2.18.0, but you'll have marshmallow 3.10.0 which is incompatible.
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
DEBUG:root:Calling callbacks: []
DEBUG:airflow.settings:Disposing DB connection pool (PID 1)
```

my custom-values.yaml file is follows.

```
###################################
# Airflow - Common Configs
###################################
# changes from tr4798 
#    dag storage from git to pvc
#    core logging/donot_pickle
#    storages are following default setup. (airflow/trident)
###################################
airflow:
  ## the airflow executor type to use
  ##
  executor: "KubernetesExecutor"
  ## environment variables for the web/scheduler/worker Pods (for airflow configs)
  ##
  config:
    AIRFLOW__CORE__LOGGING_LEVEL: "DEBUG"
    AIRFLOW__CORE__DONOT_PICKLE: "True"

    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
    AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: ""
    AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: "airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.14"
    AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
    AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: "airflow-logs"

workers:
  enabled: false # Celery workers

###################################
# Airflow - WebUI Configs
###################################
web:
  ## configs for the Service of the web Pods
  ##
  service:
    type: NodePort

###################################
# Airflow - Logs Configs
###################################
logs:
  persistence:
    enabled: true
    storageClass: basic-csi

###################################
# Airflow - DAGs Configs
###################################
dags:
  persistence:
    enabled: true
    storageClass: basic-csi
    accessMode: ReadWriteMany
    size: 1Gi
```

**Comment by sakaia** [comment]
After digging it, it seems marshmallow version is not changed in airflow-worker.
Even after pip3 update for netapp-ontap. 

```
   print(str("marshmallow version %s" % marshmallow.__version__))
    print(str("marshmallow file %s" % marshmallow.__file__))
```
Checking in airflow-worker's log, on pip it is `3.10.0`

```
marshmallow version: 2.21.0
```

- Failed Environment (by helm)

```
$ python3 --version
Python 3.6.12
$ python3 -m pip -V
pip 20.2.4 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
```

- Working Environment (by pip)

```
$ python3 --version
Python 3.6.9
$ python3 -m pip  -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

**Comment by sakaia** [comment]
It seems airflow's worker container
From seeing this, marshmallow keeps 2.21.0 not updates to 3.10.0 in python script.

```python
# Airflow marshmallow version update test

from airflow.utils.dates import days_ago
from airflow.models import DAG
from airflow.operators.python_operator import PythonOperator

af_run_dag_default_args = {
    'owner': 'sakaia'
}

## Define DAG details
af_run_dag = DAG(
    dag_id='ss0',
    default_args=af_run_dag_default_args,
    schedule_interval=None,
    start_date=days_ago(2),
    tags=['training']
)

def pythonTest(**kwargs) -> str :
    print("pythonTest")
    import sys, subprocess
    result = subprocess.check_output([sys.executable, '-m', 'pip', 'install', '--user', 'marshmallow==3.10.0'])

    import marshmallow
    print("marshmallow version: %s" % marshmallow.__version__, file=sys.stderr)
    print(str("marshmallow version %s" % marshmallow.__version__))
    return "pythonTest"

# Define DAG steps/workflow
with af_run_dag as dag :
    python_test = PythonOperator(
         task_id='python_test',
         python_callable=pythonTest,
         op_kwargs={
         },
         dag=dag
    )
```



```
[2021-02-05 01:03:50,892] {base_task_runner.py:61} DEBUG - Planning to run as the  user
[2021-02-05 01:03:50,926] {taskinstance.py:685} DEBUG - <TaskInstance: ss0.python_test 2020-12-05T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2021-02-05 01:03:50,926] {taskinstance.py:685} DEBUG - <TaskInstance: ss0.python_test 2020-12-05T00:00:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2021-02-05 01:03:50,926] {taskinstance.py:685} DEBUG - <TaskInstance: ss0.python_test 2020-12-05T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2021-02-05 01:03:50,927] {taskinstance.py:685} DEBUG - <TaskInstance: ss0.python_test 2020-12-05T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2021-02-05 01:03:50,927] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: ss0.python_test 2020-12-05T00:00:00+00:00 [queued]>
[2021-02-05 01:03:50,942] {taskinstance.py:685} DEBUG - <TaskInstance: ss0.python_test 2020-12-05T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2021-02-05 01:03:50,981] {taskinstance.py:685} DEBUG - <TaskInstance: ss0.python_test 2020-12-05T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, ('There are enough open slots in %s to execute the task', 'default_pool')
[2021-02-05 01:03:50,981] {taskinstance.py:685} DEBUG - <TaskInstance: ss0.python_test 2020-12-05T00:00:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2021-02-05 01:03:50,981] {taskinstance.py:685} DEBUG - <TaskInstance: ss0.python_test 2020-12-05T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2021-02-05 01:03:50,981] {taskinstance.py:685} DEBUG - <TaskInstance: ss0.python_test 2020-12-05T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2021-02-05 01:03:50,981] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: ss0.python_test 2020-12-05T00:00:00+00:00 [queued]>
[2021-02-05 01:03:50,982] {taskinstance.py:880} INFO -
--------------------------------------------------------------------------------
[2021-02-05 01:03:50,982] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-02-05 01:03:50,982] {taskinstance.py:882} INFO -
--------------------------------------------------------------------------------
[2021-02-05 01:03:51,021] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): python_test> on 2020-12-05T00:00:00+00:00
[2021-02-05 01:03:51,028] {standard_task_runner.py:54} INFO - Started process 70 to run task
[2021-02-05 01:03:51,077] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'ss0', 'python_test', '2020-12-05T00:00:00+00:00', '--job_id', '83', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/ss0.py', '--cfg_path', '/tmp/tmpw7b9tkee']
[2021-02-05 01:03:51,077] {standard_task_runner.py:78} INFO - Job 83: Subtask python_test
[2021-02-05 01:03:51,078] {cli_action_loggers.py:68} DEBUG - Calling callbacks: [<function default_action_log at 0x7f5aaf306b80>]
[2021-02-05 01:03:51,102] {settings.py:233} DEBUG - Setting up DB connection pool (PID 70)
[2021-02-05 01:03:51,102] {settings.py:267} DEBUG - settings.prepare_engine_args(): Using NullPool
[2021-02-05 01:03:51,174] {logging_mixin.py:112} INFO - Running <TaskInstance: ss0.python_test 2020-12-05T00:00:00+00:00 [running]> on host ss0pythontest-0998a1cf0e874fc4955190fab988a254
[2021-02-05 01:03:51,249] {__init__.py:101} DEBUG - Preparing lineage inlets and outlets
[2021-02-05 01:03:51,249] {__init__.py:137} DEBUG - inlets: [], outlets: []
[2021-02-05 01:03:51,249] {python_operator.py:103} DEBUG - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sakaia
AIRFLOW_CTX_DAG_ID=ss0
AIRFLOW_CTX_TASK_ID=python_test
AIRFLOW_CTX_EXECUTION_DATE=2020-12-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill_2020-12-05T00:00:00+00:00
[2021-02-05 01:03:51,249] {logging_mixin.py:112} INFO - pythonTest
[2021-02-05 01:03:55,258] {logging_mixin.py:112} WARNING - marshmallow version: 2.21.0
[2021-02-05 01:03:55,259] {logging_mixin.py:112} INFO - marshmallow version 2.21.0
[2021-02-05 01:03:55,260] {python_operator.py:114} INFO - Done. Returned value was: pythonTest
[2021-02-05 01:03:55,302] {__init__.py:61} DEBUG - Backend: None, Lineage called with inlets: [], outlets: []
[2021-02-05 01:03:55,330] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=ss0, task_id=python_test, execution_date=20201205T000000, start_date=20210205T010350, end_date=20210205T010355
[2021-02-05 01:03:55,905] {base_job.py:197} DEBUG - [heartbeat]
[2021-02-05 01:03:55,905] {local_task_job.py:102} INFO - Task exited with return code 0
```

**Comment by mboglesby** [comment]
I did not run into this issue with Airflow v1.10.12, however I used GitHub, not a PVC, to store my DAG code. You may want to try with the Celery Executor. There appear to be some strange quirks with the Kubernetes Executor.

**Comment by sakaia** [comment]
For changing Celery Executor, `netapp_ontap python module`  works fine with following `custom-values.yaml` definition  (which is based on minikube sample)
I planned for changing pvc to git in kubernetes executor as next trial.

```
###################################
# Airflow - Common Configs
###################################
airflow:
  image:
    tag: 1.10.14-python3.6
  ## the airflow executor type to use
  ##
  executor: "CeleryExecutor"
  ## environment variables for the web/scheduler/worker Pods (for airflow configs)
  ##
  config:
    AIRFLOW__CORE__LOGGING_LEVEL: "DEBUG"
    AIRFLOW__CORE__DONOT_PICKLE: "True"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
    AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: ""
    AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: "airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.14-python3.8"
    AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
    AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: "airflow-logs"
    PYTHONPATH: "/home/airflow/.local/lib/python3.6/site-packages"

workers:
  replicas: 1

###################################
# Airflow - WebUI Configs
###################################
web:
  service:
    type: NodePort

###################################
# Airflow - Logs Configs
###################################
# Expand size (default 1Gi)
logs:
  persistence:
    enabled: true
    storageClass: basic-csi
    size: 4Gi

###################################
# Airflow - DAGs Configs
###################################
dags:
  persistence:
    enabled: true
    storageClass: basic-csi
    accessMode: ReadWriteMany
    size: 1Gi
```

**Comment by sakaia** [comment]
I am trying to execute KubernetesExecutor with git (gitlab).
It failed in following error messages in worker node, any suggestions?
I simplify the problem to airflow tutorial.py  script, but the problem still remain.
the DAG files can see from containers `/opt/airflow/dags` repository.


```
[2021-02-24 09:37:23,265] {__init__.py:50} INFO - Using executor LocalExecutor
[2021-02-24 09:37:23,267] {dagbag.py:417} INFO - Filling up the DagBag from /opt/airflow/dags/repo/repo/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 37, in <module>
    args.func(args)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 614, in run
    dag = get_dag(args)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 168, in get_dag
    'parse.'.format(args.dag_id))
airflow.exceptions.AirflowException: dag_id could not be found: tutorial. Either the dag did not exist or it failed to parse.
```

custom-values.yaml is follows

```
###################################
# Airflow - Common Configs
###################################
airflow:
  image:
    tag: 1.10.14-python3.6
  ## the airflow executor type to use
  ##
  executor: "KubernetesExecutor"
  ## environment variables for the web/scheduler/worker Pods (for airflow configs)
  ##
  config:
    AIRFLOW__CORE__DONOT_PICKLE: "True"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
    AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "repo/"
    AIRFLOW__KUBERNETES__GIT_BRANCH: master
    AIRFLOW__KUBERNETES__GIT_SYNC_ROOT: "/opt/airflow/dags"
    AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/opt/airflow/dags"
    AIRFLOW__KUBERNETES__GIT_DAGS_VOLUME_SUBPATH: "repo/"
    AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: "airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.14-python3.6"
    AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
    AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: "airflow-logs"

workers:
  enabled: false # true is required for Celery executors

redis:
  enabled: false # true is required for Celery executors

###################################
# Airflow - WebUI Configs
###################################
web:
  ## configs for the Service of the web Pods
  ##
  service:
    type: NodePort

###################################
# Airflow - Logs Configs
###################################
# Expand size (default 1Gi)
logs:
  persistence:
    enabled: true
    storageClass: basic-csi
    size: 4Gi

###################################
# Airflow - DAGs Configs
###################################
dags:
  git:
    #ssh://git@example.com:22/REPOSITORY.git
    url: git@example.com:ai_soft/sakaiatest.git
    ref: master
    secret: airflow-git-keys
    privateKeyName: id_rsa
    repoHost: example.com
    repoPort: 22
    sshKeyscan: true

    gitSync:
      enabled: true
      refreshTime: 60
```

**Comment by sakaia** [comment]
Helm + Airflow + KubernetesExecutor + git-sync works for basic operation (pythonoperator and bashoperator) with following changes. But netapp_ontap python module vs airflow python module conflict is still remain.


- remove  (repo => null)

```
 AIRFLOW__KUBERNETES__GIT_SYNC_DEST: ""
```

Reference
https://github.com/apache/airflow/blob/1.10.12/airflow/kubernetes/worker_configuration.py#L195-L203


- error message 

```
Running <TaskInstance: snapshot2.model-snapshot 2021-01-03T00:00:00+00:00 [None]> on host snapshot2modelsnapshot-0e7206cc0b644626921f7a22ae2e5a84
ERROR: flask-appbuilder 2.3.4 requires marshmallow<3.0.0,>=2.18.0, but you'll have marshmallow 3.10.0 which is incompatible.
```

**Comment by sakaia** [comment]
Current state is same as follows (both git-sync and pvc for Kubernetes executor)

https://github.com/apache/airflow/issues/14161

**Comment by sakaia** [comment]
Finally I give up using KubernetesExecutor with git-sync. The marshmallow version conflict still remains.

The reason is

- CeleryExecutor works equivalently on ruuning sample code with python module (netapp_ontap)
- Airflow 2.0.x helm is comming shortly, so it does not need to try Airflow 1.10.x.

**Comment by sakaia** [comment]
Just one comment

After trying CeleryExecutor, I realized KubernetesPodOperator used on KubernetesExecutor.
Another workaround for conflicting marshmallow is using KubernetesPodOperator on KubernetesExecutor, when it failes on PythonOperator execution.
